from django.core.management.base import BaseCommand
from core.models import SEOPage, WorkProject

class Command(BaseCommand):
    help = "Seeds canonical SEO metadata and Work Projects from Spec Media architectural specifications"

    def handle(self, *args, **options):
        self.stdout.write("Seeding SEO Pages...")

        seo_data = [
            {
                'route_path': '/',
                'page_name': 'Homepage',
                'meta_title': 'Spec Media — Digital Architecture, Growth & Production Agency Dubai',
                'meta_description': 'Spec Media is Dubai’s premier digital agency specializing in high-performance website development, data-driven SEO, brand architecture, and AI marketing automation.',
                'canonical_url': 'https://www.spec-media.com/',
                'primary_keyword': 'digital agency dubai',
                'secondary_keywords': 'seo agency dubai, web development dubai, ai marketing dubai, creative studio uae',
                'schema_type': 'Organization',
                'is_indexable': True,
            },
            {
                'route_path': '/services/',
                'page_name': 'Services Hub',
                'meta_title': 'Services & Capabilities — Spec Media Dubai',
                'meta_description': 'Explore Spec Media’s full capabilities: SEO, custom web development, brand systems, AI automation, and paid media engineered for high-growth enterprises in Dubai and the UAE.',
                'canonical_url': 'https://www.spec-media.com/services/',
                'primary_keyword': 'digital marketing services dubai',
                'secondary_keywords': 'seo services dubai, web engineering uae, performance marketing dubai',
                'schema_type': 'CollectionPage',
                'is_indexable': True,
            },
            {
                'route_path': '/services/seo-agency-dubai/',
                'page_name': 'SEO Agency Dubai',
                'meta_title': 'SEO Agency in Dubai — Organic Growth & Search Architecture | Spec Media',
                'meta_description': 'Proven organic growth engine in Dubai. Spec Media builds scalable technical SEO, entity architecture, and revenue-driving search systems for MENA enterprises.',
                'canonical_url': 'https://www.spec-media.com/services/seo-agency-dubai/',
                'primary_keyword': 'seo agency dubai',
                'secondary_keywords': 'best seo company dubai, technical seo uae, organic growth agency',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/website-development-dubai/',
                'page_name': 'Website Development Dubai',
                'meta_title': 'Website Development Company in Dubai — High-Performance Engineering | Spec Media',
                'meta_description': 'Enterprise web development in Dubai. Next.js, Django, interactive kinetic experiences, and scalable web applications designed for maximum conversion.',
                'canonical_url': 'https://www.spec-media.com/services/website-development-dubai/',
                'primary_keyword': 'website development company dubai',
                'secondary_keywords': 'web developers dubai, custom software uae, headless web development',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/web-design-agency-dubai/',
                'page_name': 'Web Design Agency Dubai',
                'meta_title': 'Web Design Agency in Dubai — Kinetic UX & Experience Design | Spec Media',
                'meta_description': 'Award-winning web design in Dubai. We craft bespoke digital experiences, brand design systems, and responsive interfaces that establish market authority.',
                'canonical_url': 'https://www.spec-media.com/services/web-design-agency-dubai/',
                'primary_keyword': 'web design agency dubai',
                'secondary_keywords': 'ui ux design dubai, creative web agency, interactive design systems',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/digital-marketing-agency-dubai/',
                'page_name': 'Digital Marketing Agency Dubai',
                'meta_title': 'Digital Marketing Agency Dubai — Revenue & Acquisition Systems | Spec Media',
                'meta_description': 'Full-funnel digital marketing agency in Dubai. Scalable paid performance, conversion rate optimization, and integrated growth systems across the UAE and MENA.',
                'canonical_url': 'https://www.spec-media.com/services/digital-marketing-agency-dubai/',
                'primary_keyword': 'digital marketing agency dubai',
                'secondary_keywords': 'growth marketing dubai, performance marketing uae, b2b acquisition',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/ai-marketing-agency-dubai/',
                'page_name': 'AI Marketing Agency Dubai',
                'meta_title': 'AI Marketing Agency Dubai — Autonomous Media & Growth Systems | Spec Media',
                'meta_description': 'Accelerate enterprise marketing with cutting-edge AI automation, predictive audience modeling, and autonomous campaign optimization in Dubai.',
                'canonical_url': 'https://www.spec-media.com/services/ai-marketing-agency-dubai/',
                'primary_keyword': 'ai marketing agency dubai',
                'secondary_keywords': 'ai marketing automation uae, predictive marketing dubai, machine learning acquisition',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/ai-marketing-automation/',
                'page_name': 'AI Marketing Automation',
                'meta_title': 'AI Marketing Automation Services — Autonomous Workflows | Spec Media',
                'meta_description': 'Streamline acquisition pipelines and eliminate manual bottlenecks with custom AI marketing automation, CRM integrations, and intelligent lead scoring.',
                'canonical_url': 'https://www.spec-media.com/services/ai-marketing-automation/',
                'primary_keyword': 'ai marketing automation',
                'secondary_keywords': 'marketing workflow automation, lead scoring ai, automated crm workflows',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/seo-agency-uae/',
                'page_name': 'SEO Agency UAE',
                'meta_title': 'SEO Agency in UAE — National Search Dominance & Technical SEO | Spec Media',
                'meta_description': 'Strategic SEO across the United Arab Emirates. Dominate organic search in Abu Dhabi, Dubai, and the Northern Emirates with authoritative search architecture.',
                'canonical_url': 'https://www.spec-media.com/services/seo-agency-uae/',
                'primary_keyword': 'seo agency uae',
                'secondary_keywords': 'uae seo services, abu dhabi seo, national organic ranking',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/digital-marketing-agency-uae/',
                'page_name': 'Digital Marketing Agency UAE',
                'meta_title': 'Digital Marketing Agency in UAE — National Multi-Channel Growth | Spec Media',
                'meta_description': 'Scalable digital marketing solutions for UAE enterprises. Integrated brand strategy, performance media, and customer acquisition engineered for results.',
                'canonical_url': 'https://www.spec-media.com/services/digital-marketing-agency-uae/',
                'primary_keyword': 'digital marketing agency uae',
                'secondary_keywords': 'marketing companies in uae, enterprise growth agency, omni-channel media',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/google-ads-agency-dubai/',
                'page_name': 'Google Ads Agency Dubai',
                'meta_title': 'Google Ads Agency Dubai — High-ROAS Paid Search Management | Spec Media',
                'meta_description': 'Maximize ad spend efficiency with precision Google Ads management in Dubai. Advanced audience targeting, search intent capture, and conversion tracking.',
                'canonical_url': 'https://www.spec-media.com/services/google-ads-agency-dubai/',
                'primary_keyword': 'google ads agency dubai',
                'secondary_keywords': 'ppc agency dubai, paid search management uae, google advertising',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/advertising-agency-dubai/',
                'page_name': 'Advertising Agency Dubai',
                'meta_title': 'Advertising Agency Dubai — Commercial Creative & Media Buying | Spec Media',
                'meta_description': 'Impactful advertising campaigns in Dubai and the GCC. High-concept creative, strategic media planning, and cross-channel execution that commands attention.',
                'canonical_url': 'https://www.spec-media.com/services/advertising-agency-dubai/',
                'primary_keyword': 'advertising agency dubai',
                'secondary_keywords': 'ad agency dubai, creative agency gcc, commercial media buying',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/social-media-marketing-agency-dubai/',
                'page_name': 'Social Media Agency Dubai',
                'meta_title': 'Social Media Marketing Agency Dubai — Content & Audience Architecture | Spec Media',
                'meta_description': 'Build loyal brand communities in the UAE. Spec Media delivers high-velocity social content, community management, and paid social performance across MENA.',
                'canonical_url': 'https://www.spec-media.com/services/social-media-marketing-agency-dubai/',
                'primary_keyword': 'social media marketing agency dubai',
                'secondary_keywords': 'social media management uae, tiktok agency dubai, instagram growth',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/markets/mena-digital-marketing/',
                'page_name': 'MENA Digital Marketing',
                'meta_title': 'Digital Marketing Across MENA — Regional Growth & Bilingual Systems | Spec Media',
                'meta_description': 'Strategic digital expansion across the GCC and MENA. Culturally resonant bilingual marketing, multi-regional SEO, and localized customer acquisition.',
                'canonical_url': 'https://www.spec-media.com/markets/mena-digital-marketing/',
                'primary_keyword': 'mena digital marketing',
                'secondary_keywords': 'gcc digital growth, bilingual arabic english marketing, regional acquisition',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/branding-agency-dubai/',
                'page_name': 'Branding Agency Dubai',
                'meta_title': 'Branding Agency in Dubai — Brand Systems & Visual Architecture | Spec Media',
                'meta_description': 'Comprehensive brand identity design in Dubai. We architect timeless logos, design systems, typographic hierarchies, and brand guidelines for market leaders.',
                'canonical_url': 'https://www.spec-media.com/services/branding-agency-dubai/',
                'primary_keyword': 'branding agency dubai',
                'secondary_keywords': 'brand identity dubai, corporate design uae, luxury branding',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/content-creation-agency-dubai/',
                'page_name': 'Content Creation Agency Dubai',
                'meta_title': 'Content Creation Agency Dubai — High-Impact Digital Storytelling | Spec Media',
                'meta_description': 'Editorial, visual, and multimedia content creation in Dubai. Drive engagement and organic search reach with expertly produced brand assets.',
                'canonical_url': 'https://www.spec-media.com/services/content-creation-agency-dubai/',
                'primary_keyword': 'content creation agency dubai',
                'secondary_keywords': 'content studio dubai, commercial copywriting, visual storytelling uae',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/services/video-production-dubai/',
                'page_name': 'Video Production Dubai',
                'meta_title': 'Video Production Company Dubai — Cinematic Film & Commercials | Spec Media',
                'meta_description': 'World-class commercial and brand video production in Dubai. High-end cinematography, motion design, and post-production for visionary companies.',
                'canonical_url': 'https://www.spec-media.com/services/video-production-dubai/',
                'primary_keyword': 'video production dubai',
                'secondary_keywords': 'commercial film production uae, corporate video dubai, motion graphics',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/work/',
                'page_name': 'Selected Work',
                'meta_title': 'Selected Work & Case Studies — Spec Media',
                'meta_description': 'Verified client outcomes, enterprise transformations, and measurable KPIs achieved by Spec Media across Dubai, UAE, and global markets.',
                'canonical_url': 'https://www.spec-media.com/work/',
                'primary_keyword': 'digital agency case studies dubai',
                'secondary_keywords': 'spec media portfolio, client case studies, verified outcomes',
                'schema_type': 'CollectionPage',
                'is_indexable': True,
            },
            {
                'route_path': '/studio/',
                'page_name': 'The Studio',
                'meta_title': 'The Studio — People, Philosophy & Architecture | Spec Media',
                'meta_description': 'Meet the team and creative engineering philosophy driving Spec Media. Based in Dubai, operating globally at the intersection of design, code, and growth.',
                'canonical_url': 'https://www.spec-media.com/studio/',
                'primary_keyword': 'creative agency studio dubai',
                'secondary_keywords': 'spec media team, about spec media, design engineering studio',
                'schema_type': 'AboutPage',
                'is_indexable': True,
            },
            {
                'route_path': '/capabilities/',
                'page_name': 'Capabilities',
                'meta_title': 'Capabilities & Disciplines — Spec Media',
                'meta_description': 'Detailed overview of Spec Media capabilities across Brand Strategy, Campaign Production, Performance Media, and Content Systems.',
                'canonical_url': 'https://www.spec-media.com/capabilities/',
                'primary_keyword': 'digital marketing capabilities dubai',
                'secondary_keywords': 'full service agency capabilities, agency scope uae',
                'schema_type': 'Service',
                'is_indexable': True,
            },
            {
                'route_path': '/contact/',
                'page_name': 'Contact & Brief Intake',
                'meta_title': 'Contact & Brief Intake — Spec Media Dubai',
                'meta_description': 'Start a project consultation with Spec Media. Connect with our strategy, engineering, and media leads in Dubai to accelerate your commercial pipeline.',
                'canonical_url': 'https://www.spec-media.com/contact/',
                'primary_keyword': 'contact spec media dubai',
                'secondary_keywords': 'book strategy call dubai, hire digital agency uae, submit project brief',
                'schema_type': 'ContactPage',
                'is_indexable': True,
            }
        ]

        for item in seo_data:
            obj, created = SEOPage.objects.update_or_create(
                route_path=item['route_path'],
                defaults=item
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"  {action} SEO page: {obj.route_path}")

        self.stdout.write("\nSeeding Work Projects...")
        works_data = [
            {
                'title': 'Aether MENA — Regional Organic Search Dominance',
                'slug': 'aether-mena-growth',
                'client': 'Aether Technologies',
                'discipline': 'SEO & Organic Growth',
                'market': 'Dubai / MENA',
                'year': '2026',
                'hero_image': 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
                'summary': 'Architected enterprise entity SEO and bilingual Arabic/English content clusters driving multi-region organic capture across the UAE and Saudi Arabia.',
                'challenge': 'Aether struggled with regional keyword cannibalization and low indexation across GCC territories, missing out on high-intent enterprise commercial search queries.',
                'solution': 'Engineered a unified canonical architecture, implemented Schema.org Service and Organization entities, and deployed 45 authoritative regional knowledge hubs.',
                'deliverables': 'Technical SEO Audit, Entity Graph Architecture, Bilingual Content Clusters, Core Web Vitals Optimization',
                'kpis': '+340% Organic Search Traffic; #1 Organic Rank in UAE; 3.8x Pipeline Leads; 0.9s Mobile LCP',
                'is_featured': True,
                'sort_order': 1,
            },
            {
                'title': 'Kinetics Dubai — Real-Time 3D Digital System',
                'slug': 'kinetics-dubai-3d',
                'client': 'Kinetics Luxury Group',
                'discipline': 'Web & Experience Systems',
                'market': 'Dubai',
                'year': '2026',
                'hero_image': 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
                'summary': 'Designed and developed a 60fps kinetic WebGL showroom with procedural canvas scrubbing, custom GLSL shaders, and sub-second headless navigation.',
                'challenge': 'The client needed an unforgettable digital flagship to stand out in the ultra-competitive Dubai luxury market without sacrificing mobile page load speed.',
                'solution': 'Built custom canvas frame scrubbing with pre-computed assets and unified state management, maintaining 60fps on mobile and 100/100 Lighthouse performance.',
                'deliverables': 'Custom Canvas Engine, GLSL Shaders, Interactive 3D Flagship, Headless CMS Integration',
                'kpis': '18ms Render Latency; 4.9x Engagement Duration; +88% Direct Inquiries; 100/100 Performance Score',
                'is_featured': True,
                'sort_order': 2,
            },
            {
                'title': 'Hyperion AI — Autonomous Marketing Pipeline',
                'slug': 'hyperion-ai-automation',
                'client': 'Hyperion Capital',
                'discipline': 'AI Marketing & Automation',
                'market': 'Global',
                'year': '2026',
                'hero_image': 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
                'summary': 'Implemented autonomous marketing pipelines with predictive audience segmentation, automated CRM synchronization, and multi-channel lead enrichment.',
                'challenge': 'Hyperion’s sales team spent over 25 hours per week manually vetting and enriching unqualified inbound leads from cross-border institutional campaigns.',
                'solution': 'Integrated Supabase event webhooks, automated vector-based lead scoring, and orchestrated real-time CRM routing with zero human overhead.',
                'deliverables': 'Autonomous Workflow Architecture, Supabase CRM Engine, Real-time Lead Scoring, Conversion Tracking Webhooks',
                'kpis': '62% Reduction in CAC; 12,000+ Automated Leads Processed; 4.4x Conversion Lift; 99.98% Pipeline Uptime',
                'is_featured': True,
                'sort_order': 3,
            },
            {
                'title': 'Vanguard Media — High-Performance Acquisition',
                'slug': 'vanguard-media-acquisition',
                'client': 'Vanguard Holdings',
                'discipline': 'Paid Performance Media',
                'market': 'UAE',
                'year': '2025',
                'hero_image': 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
                'summary': 'Multi-channel paid search and paid social campaigns across Google Ads, LinkedIn, and Meta targeting C-suite decision makers in the UAE.',
                'challenge': 'High customer acquisition costs and audience saturation on standard PPC ad formats led to diminishing return on ad spend (ROAS).',
                'solution': 'Re-architected intent-driven landing pages, implemented server-side conversion tracking, and deployed dynamic ad creative variations.',
                'deliverables': 'Google Ads Architecture, High-Intent Conversion Landing Pages, Server-Side CAPI, Creative Testing Matrix',
                'kpis': '4.8x Blended ROAS; $2.4M Attributed Pipeline; 24% Lower CPA; +185% Qualified Consultation Rate',
                'is_featured': False,
                'sort_order': 4,
            },
            {
                'title': 'Nox Atelier — Brand Identity & Design System',
                'slug': 'nox-atelier-brand',
                'client': 'Nox Haute Horlogerie',
                'discipline': 'Brand Architecture & Design',
                'market': 'Dubai / Global',
                'year': '2025',
                'hero_image': 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop',
                'summary': 'End-to-end brand identity architecture, typographic scale, physical packaging guidelines, and digital design system for an independent horology maison.',
                'challenge': 'Establishing an immediate aura of luxury heritage and surgical mechanical precision for a newly founded bespoke watchmaker in Dubai.',
                'solution': 'Engineered a restrained, brutalist-elegance brand system featuring custom monospaced typography, metallic foil specifications, and digital brand guidelines.',
                'deliverables': 'Brand Architecture Book, Design Tokens & System, Packaging Specifications, Digital Design Guidelines',
                'kpis': 'Red Dot Design Recognition; 140+ Brand Assets Deployed; 100% Brand Recognition in GCC Collector Community',
                'is_featured': False,
                'sort_order': 5,
            }
        ]

        for item in works_data:
            obj, created = WorkProject.objects.update_or_create(
                slug=item['slug'],
                defaults=item
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"  {action} Work project: {obj.title}")

        self.stdout.write(self.style.SUCCESS("Successfully seeded all SEO Pages and Work Projects!"))
