# Generated by Django 4.2.30 on 2026-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_path', models.CharField(help_text='Canonical URL path, e.g. / or /services/seo-agency-dubai/', max_length=255, unique=True)),
                ('page_name', models.CharField(help_text='Human-readable title in the CMS', max_length=150)),
                ('meta_title', models.CharField(help_text='Browser <title> and Google search snippet title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Search engine meta description (150-160 chars)')),
                ('canonical_url', models.CharField(blank=True, help_text='Full canonical URL (e.g. https://www.spec-media.com/...)', max_length=500)),
                ('primary_keyword', models.CharField(blank=True, help_text='Primary commercial search term', max_length=150)),
                ('secondary_keywords', models.TextField(blank=True, help_text='Comma-separated secondary keywords')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description')),
                ('og_image_url', models.CharField(blank=True, help_text='Social preview image URL', max_length=500)),
                ('schema_type', models.CharField(choices=[('Organization', 'Organization'), ('Service', 'Service'), ('WebPage', 'WebPage'), ('CollectionPage', 'CollectionPage'), ('ContactPage', 'ContactPage'), ('AboutPage', 'AboutPage')], default='Service', max_length=50)),
                ('is_indexable', models.BooleanField(default=True, help_text='Whether search engines should index this route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'ordering': ['route_path'],
            },
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project / Case Study title', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug (e.g. aether-hyperion-dubai)', max_length=200, unique=True)),
                ('client', models.CharField(help_text='Client brand or sector descriptor', max_length=150)),
                ('discipline', models.CharField(choices=[('SEO & Organic Growth', 'SEO & Organic Growth'), ('Web & Experience Systems', 'Web & Experience Systems'), ('AI Marketing & Automation', 'AI Marketing & Automation'), ('Brand Architecture & Design', 'Brand Architecture & Design'), ('Paid Performance Media', 'Paid Performance Media'), ('Content & Motion Production', 'Content & Motion Production')], default='Web & Experience Systems', max_length=100)),
                ('market', models.CharField(choices=[('Dubai', 'Dubai'), ('UAE', 'UAE'), ('MENA', 'MENA'), ('Global', 'Global')], default='Dubai', max_length=100)),
                ('year', models.CharField(default='2026', max_length=10)),
                ('hero_image', models.CharField(blank=True, help_text='Hero image URL or data URI', max_length=500)),
                ('summary', models.TextField(help_text='Short teaser summary displayed on cards')),
                ('challenge', models.TextField(blank=True, help_text='The commercial challenge faced by the client')),
                ('solution', models.TextField(blank=True, help_text='The strategic execution by Spec Media')),
                ('deliverables', models.TextField(blank=True, help_text='Comma-separated deliverables (e.g. Design System, Custom Shaders, Headless CMS)')),
                ('kpis', models.TextField(blank=True, help_text='Semicolon-separated KPI results (e.g. +312% Organic Growth; 4.8x ROAS; #1 Dubai Ranking)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature prominently on homepage and work grid')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display priority (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Project',
                'verbose_name_plural': 'Work Projects',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
