# Generated by Django 4.2.30 on 2026-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SPEC MEDIA', max_length=150)),
                ('logo_image', models.TextField(blank=True, help_text='Site logo base64 data URI, SVG, or image URL')),
                ('logo_text', models.CharField(default='SPEC MEDIA', max_length=100)),
                ('favicon_image', models.TextField(blank=True, help_text='Favicon base64 data URI, ICO, or SVG')),
                ('hero_headline', models.CharField(default='You feel the brand before it speaks®', max_length=255)),
                ('hero_subheadline', models.TextField(default='Placeholder copy. Spec Media builds campaigns for companies that care how things feel and how they are perceived over time.')),
                ('hero_badge', models.CharField(default='01 / HERO', max_length=100)),
                ('hero_cta_text', models.CharField(default='[ SCROLL DOWN ]', max_length=100)),
                ('hero_media_type', models.CharField(choices=[('canvas', 'Procedural Kinetic Canvas Engine'), ('image', 'Custom Photo / Graphic'), ('video', 'Custom Video Loop')], default='canvas', max_length=50)),
                ('hero_media_url', models.TextField(blank=True, help_text='Uploaded photo or video data URI or URL for hero showcase')),
                ('contact_email', models.CharField(default='hello@specmedia.co', max_length=150)),
                ('contact_phone', models.CharField(default='+971 4 000 0000', max_length=100)),
                ('contact_address', models.CharField(default='Dubai Design District, Building 3, Dubai, UAE', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='workproject',
            name='hero_image',
            field=models.TextField(blank=True, help_text='Hero image URL or data URI'),
        ),
    ]
