# Generated by Django 4.2.30 on 2026-09-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_capability_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='client_reviews',
            field=models.JSONField(blank=True, default=list, help_text='Custom client reviews for Instagram cards'),
        ),
    ]
