# Generated by Django 4.2.30 on 2026-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_client_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reel_video_url',
            field=models.CharField(blank=True, default='/static/reference_video.mp4', help_text='The Reel background showcase video', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scene2_badge',
            field=models.CharField(blank=True, default='02 / SCENE 02', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scene2_hint',
            field=models.CharField(blank=True, default='keep scrolling or drag mouse to play · frame pauses instantly', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scene2_video_url',
            field=models.CharField(blank=True, default='/static/scene2_brain.mp4', help_text='Scene 02 brain scrub video loop or canvas fallback', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='studio_headline',
            field=models.CharField(blank=True, default='Built for brands that demand cultural resonance.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='studio_subheadline',
            field=models.TextField(blank=True, default='Spec Media is an independent creative studio operating at the intersection of cinematic craft, digital infrastructure, and high-velocity performance marketing.'),
        ),
    ]
