# Generated by Django 4.2.30 on 2026-09-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_reel_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='scene2_sprite_url',
            field=models.CharField(blank=True, default='https://afbvxvknlgsyinqdcend.supabase.co/storage/v1/object/public/media/sprites/scene2_sprite.jpg', help_text='Scene 02 100-frame 60fps synchronous sprite sheet URL', max_length=500),
        ),
    ]
