# Generated by Django 4.2.30 on 2026-09-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_scene2_sprite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workproject',
            name='challenge_ar',
            field=models.TextField(blank=True, help_text='Arabic commercial challenge'),
        ),
        migrations.AddField(
            model_name='workproject',
            name='client_ar',
            field=models.CharField(blank=True, help_text='Arabic client name', max_length=150),
        ),
        migrations.AddField(
            model_name='workproject',
            name='deliverables_ar',
            field=models.TextField(blank=True, help_text='Comma-separated Arabic deliverables'),
        ),
        migrations.AddField(
            model_name='workproject',
            name='kpis_ar',
            field=models.TextField(blank=True, help_text='Semicolon-separated Arabic KPIs'),
        ),
        migrations.AddField(
            model_name='workproject',
            name='solution_ar',
            field=models.TextField(blank=True, help_text='Arabic strategic solution'),
        ),
        migrations.AddField(
            model_name='workproject',
            name='summary_ar',
            field=models.TextField(blank=True, help_text='Arabic summary displayed on cards'),
        ),
        migrations.AddField(
            model_name='workproject',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Arabic project title', max_length=200),
        ),
    ]
